// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Initial_Gui_Testing', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Initial_Gui_Testing', async function() {
    // Test name: Initial_Gui_Testing
    // Step # | name | target | value
    // 1 | open | /all | 
    await driver.get("http://localhost:5173/all")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    // 3 | mouseDownAt | css=.overflow-x-auto | 843.6374969482422,42.40000009536743
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 4 | mouseMoveAt | css=.overflow-x-auto | 843.6374969482422,42.40000009536743
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseUpAt | css=.overflow-x-auto | 843.6374969482422,42.40000009536743
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 6 | click | css=.pr-10 | 
    await driver.findElement(By.css(".pr-10")).click()
    // 7 | click | css=.lg\3Apx-10 | 
    await driver.findElement(By.css(".lg\\3Apx-10")).click()
    // 8 | click | css=.hidden > .lucide | 
    await driver.findElement(By.css(".hidden > .lucide")).click()
    // 9 | click | css=.hidden .p-2 path:nth-child(2) | 
    await driver.findElement(By.css(".hidden .p-2 path:nth-child(2)")).click()
    // 10 | click | css=.hover\3A bg-red-700 | 
    await driver.findElement(By.css(".hover\\3A bg-red-700")).click()
    // 11 | mouseOver | css=.hover\3A bg-red-700 | 
    {
      const element = await driver.findElement(By.css(".hover\\3A bg-red-700"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | mouseOut | css=.hover\3A bg-red-700 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 13 | runScript | window.scrollTo(0,857.5999755859375) | 
    await driver.executeScript("window.scrollTo(0,857.5999755859375)")
    // 14 | click | css=.close-btn | 
    await driver.findElement(By.css(".close-btn")).click()
    // 15 | click | id=🔒 Please login to view more headlines | 
    await driver.findElement(By.id("🔒 Please login to view more headlines")).click()
    // 16 | click | css=.h-10 | 
    await driver.findElement(By.css(".h-10")).click()
    // 17 | click | css=.relative:nth-child(1) > .inset-0 | 
    await driver.findElement(By.css(".relative:nth-child(1) > .inset-0")).click()
    // 18 | click | css=.close-btn | 
    await driver.findElement(By.css(".close-btn")).click()
    // 19 | click | css=.h-full:nth-child(5) .flex:nth-child(1) > .lucide | 
    await driver.findElement(By.css(".h-full:nth-child(5) .flex:nth-child(1) > .lucide")).click()
    // 20 | mouseOver | css=.h-full:nth-child(5) .flex:nth-child(1) > .lucide | 
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(5) .flex:nth-child(1) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 21 | mouseOut | css=.h-full:nth-child(5) .flex:nth-child(1) > .lucide | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 22 | click | css=.Toastify__close-button > svg | 
    await driver.findElement(By.css(".Toastify__close-button > svg")).click()
    // 23 | click | css=.h-full:nth-child(5) .flex:nth-child(2) > .lucide | 
    await driver.findElement(By.css(".h-full:nth-child(5) .flex:nth-child(2) > .lucide")).click()
    // 24 | mouseOver | css=.h-full:nth-child(5) .flex:nth-child(2) > .lucide | 
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(5) .flex:nth-child(2) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 25 | mouseOut | css=.h-full:nth-child(5) .flex:nth-child(2) > .lucide | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 26 | click | css=.Toastify__close-button > svg | 
    await driver.findElement(By.css(".Toastify__close-button > svg")).click()
    // 27 | click | css=.h-full:nth-child(5) .p-2\.5:nth-child(3) > .lucide | 
    await driver.findElement(By.css(".h-full:nth-child(5) .p-2\\.5:nth-child(3) > .lucide")).click()
    // 28 | mouseOver | css=.h-full:nth-child(5) .p-2\.5:nth-child(3) > .lucide | 
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(5) .p-2\\.5:nth-child(3) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 29 | mouseOut | css=.h-full:nth-child(5) .p-2\.5:nth-child(3) > .lucide | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 30 | click | css=.Toastify__close-button > svg | 
    await driver.findElement(By.css(".Toastify__close-button > svg")).click()
    // 31 | click | css=.h-full:nth-child(5) .absolute .flex:nth-child(4) | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 32 | storeWindowHandle | root | 
    await driver.findElement(By.css(".h-full:nth-child(5) .absolute .flex:nth-child(4)")).click()
    // 33 | selectWindow | handle=${win6166} | 
    vars["win6166"] = await waitForWindow(2000)
    // 34 | selectWindow | handle=${root} | 
    vars["root"] = await driver.getWindowHandle()
    // 35 | click | css=.absolute > .lucide | 
    await driver.switchTo().window(vars["win6166"])
    // 36 | click | css=.lg\3Ainline-flex | 
    await driver.switchTo().window(vars["root"])
    // 37 | click | css=.hidden > .p-4 > .w-full | 
    await driver.findElement(By.css(".absolute > .lucide")).click()
    // 38 | click | css=input:nth-child(2) | 
    await driver.findElement(By.css(".lg\\3Ainline-flex")).click()
    // 39 | type | css=input:nth-child(2) | gtpbnm99@gmail.com
    await driver.findElement(By.css(".hidden > .p-4 > .w-full")).click()
    // 40 | click | css=input:nth-child(4) | 
    await driver.findElement(By.css("input:nth-child(2)")).click()
    // 41 | type | css=input:nth-child(4) | Tt@123456789
    await driver.findElement(By.css("input:nth-child(2)")).sendKeys("gtpbnm99@gmail.com")
    // 42 | click | id=showPassLogin | 
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 43 | click | css=input:nth-child(4) | 
    await driver.findElement(By.css("input:nth-child(4)")).sendKeys("Tt@123456789")
    // 44 | click | linkText=Sign up | 
    await driver.findElement(By.id("showPassLogin")).click()
    // 45 | click | id=showPassSignup | 
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 46 | click | css=input:nth-child(12) | 
    await driver.findElement(By.linkText("Sign up")).click()
    // 47 | click | css=input:nth-child(10) | 
    await driver.findElement(By.id("showPassSignup")).click()
    // 48 | click | css=input:nth-child(8) | 
    await driver.findElement(By.css("input:nth-child(12)")).click()
    // 49 | click | css=input:nth-child(6) | 
    await driver.findElement(By.css("input:nth-child(10)")).click()
    // 50 | click | css=input:nth-child(6) | 
    await driver.findElement(By.css("input:nth-child(8)")).click()
    // 51 | click | css=input:nth-child(4) | 
    await driver.findElement(By.css("input:nth-child(6)")).click()
    // 52 | click | css=input:nth-child(2) | 
    await driver.findElement(By.css("input:nth-child(6)")).click()
    // 53 | click | linkText=Login | 
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 54 | click | css=input:nth-child(2) | 
    await driver.findElement(By.css("input:nth-child(2)")).click()
    // 55 | type | css=input:nth-child(2) | gtpbnm99@gmail.com
    await driver.findElement(By.linkText("Login")).click()
    // 56 | click | css=input:nth-child(4) | 
    await driver.findElement(By.css("input:nth-child(2)")).click()
    // 57 | type | css=input:nth-child(4) | Tt123456789
    await driver.findElement(By.css("input:nth-child(2)")).sendKeys("gtpbnm99@gmail.com")
    // 58 | click | id=showPassLogin | 
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 59 | click | css=input:nth-child(4) | 
    await driver.findElement(By.css("input:nth-child(4)")).sendKeys("Tt123456789")
    // 60 | click | css=.login-btn | 
    await driver.findElement(By.id("showPassLogin")).click()
    // 61 | click | css=input:nth-child(4) | 
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 62 | click | css=input:nth-child(4) | 
    await driver.findElement(By.css(".login-btn")).click()
    // 63 | type | css=input:nth-child(4) | Tt@123456789
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 64 | click | css=.login-btn | 
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 65 | click | css=.hidden .flex > .text-sm:nth-child(2) | 
    await driver.findElement(By.css("input:nth-child(4)")).sendKeys("Tt@123456789")
    // 66 | click | css=.hover\3A bg-red-100 | 
    await driver.findElement(By.css(".login-btn")).click()
    // 67 | click | name=name | 
    await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)")).click()
    // 68 | click | name=email | 
    await driver.findElement(By.css(".hover\\3A bg-red-100")).click()
    // 69 | click | name=message | 
    await driver.findElement(By.name("name")).click()
    // 70 | click | css=.hidden > .lucide | 
    await driver.findElement(By.name("email")).click()
    // 71 | click | css=.hidden .flex > .text-sm:nth-child(2) | 
    await driver.findElement(By.name("message")).click()
    // 72 | mouseOver | css=.hidden .flex > .text-sm:nth-child(2) | 
    await driver.findElement(By.css(".hidden > .lucide")).click()
    // 73 | mouseOut | css=.hidden .space-y-2 > .flex > .text-sm:nth-child(2) | 
    await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)")).click()
    // 74 | click | css=.justify-between > .text-xs | 
    {
      const element = await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 75 | mouseOver | css=.justify-between > .text-xs | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 76 | mouseOut | css=.justify-between > .text-xs | 
    await driver.findElement(By.css(".justify-between > .text-xs")).click()
    // 77 | click | css=.flex-1:nth-child(1) | 
    {
      const element = await driver.findElement(By.css(".justify-between > .text-xs"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 78 | click | css=.justify-between > .text-xs | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 79 | click | css=.hidden .space-y-2 > .flex > .text-sm:nth-child(2) | 
    await driver.findElement(By.css(".flex-1:nth-child(1)")).click()
    // 80 | click | css=.hidden .flex > .text-sm:nth-child(2) | 
    await driver.findElement(By.css(".justify-between > .text-xs")).click()
    // 81 | click | css=.w-11 | 
    await driver.findElement(By.css(".hidden .space-y-2 > .flex > .text-sm:nth-child(2)")).click()
    // 82 | click | css=.hidden .flex > .text-sm:nth-child(2) | 
    await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)")).click()
    // 83 | click | css=.top-0\.5 | 
    await driver.findElement(By.css(".w-11")).click()
    // 84 | click | css=.hidden > .overflow-y-auto .w-full:nth-child(1) | 
    await driver.findElement(By.css(".hidden .flex > .text-sm:nth-child(2)")).click()
    // 85 | click | css=.hidden .w-full:nth-child(2) > span | 
    await driver.findElement(By.css(".top-0\\.5")).click()
    // 86 | mouseOver | css=.hidden .w-full:nth-child(2) | 
    await driver.findElement(By.css(".hidden > .overflow-y-auto .w-full:nth-child(1)")).click()
    // 87 | mouseOut | css=.hidden .w-full:nth-child(2) | 
    await driver.findElement(By.css(".hidden .w-full:nth-child(2) > span")).click()
    // 88 | click | css=.hidden .p-6 > .bg-gradient-to-br | 
    {
      const element = await driver.findElement(By.css(".hidden .w-full:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 89 | click | css=.hidden .p-2 > .lucide | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 90 | click | css=.whitespace-nowrap:nth-child(1) | 
    await driver.findElement(By.css(".hidden .p-6 > .bg-gradient-to-br")).click()
    // 91 | mouseDownAt | css=.overflow-x-auto | 735.6374969482422,40.40000009536743
    await driver.findElement(By.css(".hidden .p-2 > .lucide")).click()
    // 92 | mouseMoveAt | css=.overflow-x-auto | 735.6374969482422,40.40000009536743
    await driver.findElement(By.css(".whitespace-nowrap:nth-child(1)")).click()
    // 93 | mouseUpAt | css=.overflow-x-auto | 735.6374969482422,40.40000009536743
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 94 | click | css=.flex:nth-child(10) | 
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 95 | click | css=.flex:nth-child(9) > span | 
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 96 | click | css=.flex:nth-child(8) > span | 
    await driver.findElement(By.css(".flex:nth-child(10)")).click()
    // 97 | click | css=.flex:nth-child(7) > span | 
    await driver.findElement(By.css(".flex:nth-child(9) > span")).click()
    // 98 | click | css=.lucide-heart | 
    await driver.findElement(By.css(".flex:nth-child(8) > span")).click()
    // 99 | mouseOver | css=.flex:nth-child(6) > span | 
    await driver.findElement(By.css(".flex:nth-child(7) > span")).click()
    // 100 | click | css=.flex:nth-child(6) > span | 
    await driver.findElement(By.css(".lucide-heart")).click()
    // 101 | mouseOut | css=.bg-red-50 > span | 
    {
      const element = await driver.findElement(By.css(".flex:nth-child(6) > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 102 | click | css=.flex:nth-child(5) > span | 
    await driver.findElement(By.css(".flex:nth-child(6) > span")).click()
    // 103 | click | css=.flex:nth-child(4) > span | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 104 | mouseOver | css=.gap-2:nth-child(3) | 
    await driver.findElement(By.css(".flex:nth-child(5) > span")).click()
    // 105 | mouseOut | css=.gap-2:nth-child(3) | 
    await driver.findElement(By.css(".flex:nth-child(4) > span")).click()
    // 106 | click | css=.gap-2:nth-child(3) > span | 
    {
      const element = await driver.findElement(By.css(".gap-2:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 107 | mouseOver | css=.flex:nth-child(4) > span | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 108 | mouseOut | css=.flex:nth-child(4) > span | 
    await driver.findElement(By.css(".gap-2:nth-child(3) > span")).click()
    // 109 | mouseDownAt | css=.overflow-x-auto | 64.63749694824219,58.40000009536743
    {
      const element = await driver.findElement(By.css(".flex:nth-child(4) > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 110 | mouseMoveAt | css=.overflow-x-auto | 64.63749694824219,58.40000009536743
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 111 | mouseUpAt | css=.overflow-x-auto | 64.63749694824219,58.40000009536743
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 112 | click | css=.relative:nth-child(1) > .inset-0 | 
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 113 | runScript | window.scrollTo(0,200) | 
    {
      const element = await driver.findElement(By.css(".overflow-x-auto"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 114 | click | css=.h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide | 
    await driver.findElement(By.css(".relative:nth-child(1) > .inset-0")).click()
    // 115 | click | css=.focus\3A border-red-500 | 
    await driver.executeScript("window.scrollTo(0,200)")
    // 116 | type | css=.focus\3A border-red-500 | nice article
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(1) > .lucide")).click()
    // 117 | click | css=.hover\3A bg-red-500 | 
    await driver.findElement(By.css(".focus\\3A border-red-500")).click()
    // 118 | click | css=.h-full:nth-child(1) > .relative > .absolute .p-2\.5:nth-child(3) | 
    await driver.findElement(By.css(".focus\\3A border-red-500")).sendKeys("nice article")
    // 119 | click | css=.lucide-volume-x | 
    await driver.findElement(By.css(".hover\\3A bg-red-500")).click()
    // 120 | click | css=.h-full:nth-child(1) > .relative > .absolute .flex:nth-child(2) > .lucide | 
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .p-2\\.5:nth-child(3)")).click()
    // 121 | mouseOver | css=.h-full:nth-child(1) > .relative > .absolute .flex:nth-child(2) > .lucide | 
    await driver.findElement(By.css(".lucide-volume-x")).click()
    // 122 | mouseOut | css=.h-full:nth-child(1) > .relative > .absolute .flex:nth-child(2) > .lucide | 
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(2) > .lucide")).click()
    // 123 | click | css=.bg-gray-700 | 
    {
      const element = await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(2) > .lucide"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 124 | type | css=.bg-gray-700 | gujarati
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 125 | click | css=.text-left | 
    await driver.findElement(By.css(".bg-gray-700")).click()
    // 126 | click | css=.h-full:nth-child(1) > .relative > .absolute .p-2\.5:nth-child(3) > .lucide | 
    await driver.findElement(By.css(".bg-gray-700")).sendKeys("gujarati")
    // 127 | click | css=.bg-red-500\/50 | 
    await driver.findElement(By.css(".text-left")).click()
    // 128 | click | css=.h-full:nth-child(1) > .relative > .absolute .flex:nth-child(4) | 
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .p-2\\.5:nth-child(3) > .lucide")).click()
    // 129 | selectWindow | handle=${win1458} | 
    await driver.findElement(By.css(".bg-red-500\\/50")).click()
    // 130 | selectWindow | handle=${root} | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 131 | click | css=.absolute > .lucide | 
    await driver.findElement(By.css(".h-full:nth-child(1) > .relative > .absolute .flex:nth-child(4)")).click()
    vars["win1458"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win1458"])
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.css(".absolute > .lucide")).click()
  })
})
